# Generated by Django 4.0.5 on 2022-06-24 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_order_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='order_item', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
