# Generated by Django 4.0.5 on 2022-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
