# Generated by Django 4.0.5 on 2022-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shop_image_link_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
