# Generated by Django 4.0.5 on 2022-07-02 09:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image_link_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='order_items', to='store.order'),
        ),
    ]
