# Generated by Django 4.0.5 on 2022-07-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_is_checkout_cart_shop_cart_updated_at_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='order_status',
        ),
    ]
