# Generated by Django 4.0.5 on 2022-07-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_orderitem_unit_price_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop',
        ),
    ]
