# Generated by Django 4.0.5 on 2022-07-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_cart_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='store.customerorderhistory')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.orderitem')),
            ],
        ),
    ]
