# Generated by Django 4.0.5 on 2022-07-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerordereditem',
            old_name='ordered_item',
            new_name='order_item',
        ),
    ]
