# Generated by Django 4.0.5 on 2022-07-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_ordered_item_customerordereditem_order_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrderHistory',
            new_name='OrderHistory',
        ),
    ]
