# Generated by Django 4.0.5 on 2022-07-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_customerorderhistory_orderhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrderedItem',
            new_name='OrderHistoryItem',
        ),
    ]
